### PR TITLE
pycvvdp: Sort the output for wildcharchars

### PR DESCRIPTION
**Pull request by vibhoothi**
This is problematic if we do not sort when we feed two folders.
Python does not care about frame orders, but we care, so in some cases,
it was comparing Frame 2 with Frame 90. So to be correct, we
sort it before returning the list.

PS: Will rebase once #7 is merged

### CODE REVIEW

**Review by mantiuk — COMMENTED** [review]
Thank you for contributing this pull request. 

The problem is clear but the solution is not ideal. It introduced a dependency on pandas, which we would rather avoid. It also adds duplicate functionality with the `--save` argument. 

The new code now sorts the file names after the wildcard expansions. If this does not solve the problem, please use the interactive mode: 

https://github.com/gfxdisp/ColorVideoVDP?tab=readme-ov-file#interactive-mode

**Comment by vibhoothi** [comment]
What do you mean duplicate functionality of save?
Save was introduced in this PR, not sure about duplicate functionality, there was no way to save as csv in the path.


I think interactive mode is orthogonal to this PR.

We can always kill pandas if we need, it will be useful if you prefer to match like how modern tools work which supports CSV/XML/JSON and others. So it can be easy adjusted, while if we use classic CSV/filebased IO, it will be harder to support more output formats in future,
See VMAF tool for reference of multi output format

**Comment by vibhoothi** [comment]
I  also see you have https://github.com/gfxdisp/ColorVideoVDP/commit/b854cfcfed38d2936908eed57687ee830d0aba2f which is essentially this PR commit https://github.com/gfxdisp/ColorVideoVDP/pull/9/commits/f0814276597f52d8946849eb424c4eddebbe3b87 but a copy of it without reference to the original commit;)

**Comment by mantiuk** [comment]
Yes, sorry, I missed https://github.com/gfxdisp/ColorVideoVDP/commit/f0814276597f52d8946849eb424c4eddebbe3b87

We will look into how to unify the interface with VMAF at some point. But this will be a separate PR. 

Right now, you can use `--quiet` argument to get the JOD scores alone.

**Comment by vibhoothi** [comment]
https://github.com/gfxdisp/ColorVideoVDP/commit/b854cfcfed38d2936908eed57687ee830d0aba2f addresses this

**Pull request closed without merging**
